neighborhoods = {
    '10453': 'Central Bronx',
    '10457': 'Central Bronx',
    '10460': 'Central Bronx',
    '10458': 'Bronx Park and Fordham',
    '10467': 'Bronx Park and Fordham',
    '10468': 'Bronx Park and Fordham',
    '10451': 'High Bridge and Morrisania',
    '10452': 'High Bridge and Morrisania',
    '10456': 'High Bridge and Morrisania',
    '10454': 'Hunts Point and Mott Haven',
    '10455': 'Hunts Point and Mott Haven',
    '10459': 'Hunts Point and Mott Haven',
    '10474': 'Hunts Point and Mott Haven',
    '10463': 'Kingsbridge and Riverdale',
    '10471': 'Kingsbridge and Riverdale',
    '10466': 'Northeast Bronx',
    '10469': 'Northeast Bronx',
    '10470': 'Northeast Bronx',
    '10475': 'Northeast Bronx',
    '10461': 'Southeast Bronx',
    '10462': 'Southeast Bronx',
    '10464': 'Southeast Bronx',
    '10465': 'Southeast Bronx',
    '10472': 'Southeast Bronx',
    '10473': 'Southeast Bronx',
    '11212': 'Central Brooklyn',
    '11213': 'Central Brooklyn',
    '11216': 'Central Brooklyn',
    '11233': 'Central Brooklyn',
    '11238': 'Central Brooklyn',
    '11249': 'Northwest Brooklyn',
    '11209': 'Southwest Brooklyn',
    '11214': 'Southwest Brooklyn',
    '11228': 'Southwest Brooklyn',
    '11204': 'Borough Park',
    '11218': 'Borough Park',
    '11219': 'Borough Park',
    '11230': 'Borough Park',
    '11234': 'Canarsie and Flatlands',
    '11236': 'Canarsie and Flatlands',
    '11239': 'Canarsie and Flatlands',
    '11223': 'Southern Brooklyn',
    '11224': 'Southern Brooklyn',
    '11229': 'Southern Brooklyn',
    '11235': 'Southern Brooklyn',
    '11201': 'Northwest Brooklyn',
    '11205': 'Northwest Brooklyn',
    '11215': 'Northwest Brooklyn',
    '11217': 'Northwest Brooklyn',
    '11231': 'Northwest Brooklyn',
    '11203': 'Flatbush',
    '11210': 'Flatbush',
    '11225': 'Flatbush',
    '11226': 'Flatbush',
    '11207': 'East New York and New Lots',
    '11208': 'East New York and New Lots',
    '11211': 'Greenpoint',
    '11222': 'Greenpoint',
    '11220': 'Sunset Park',
    '11232': 'Sunset Park',
    '11206': 'Bushwick and Williamsburg',
    '11221': 'Bushwick and Williamsburg',
    '11237': 'Bushwick and Williamsburg',
    '10026': 'Central Harlem',
    '10027': 'Central Harlem',
    '10030': 'Central Harlem',
    '10037': 'Central Harlem',
    '10039': 'Central Harlem',
    '10001': 'Chelsea and Clinton',
    '10011': 'Chelsea and Clinton',
    '10018': 'Chelsea and Clinton',
    '10019': 'Chelsea and Clinton',
    '10020': 'Chelsea and Clinton',
    '10036': 'Chelsea and Clinton',
    '10029': 'East Harlem',
    '10035': 'East Harlem',
    '10010': 'Gramercy Park and Murray Hill',
    '10016': 'Gramercy Park and Murray Hill',
    '10017': 'Gramercy Park and Murray Hill',
    '10022': 'Gramercy Park and Murray Hill',
    '10012': 'Greenwich Village and Soho',
    '10013': 'Greenwich Village and Soho',
    '10014': 'Greenwich Village and Soho',
    '10004': 'Lower Manhattan',
    '10005': 'Lower Manhattan',
    '10006': 'Lower Manhattan',
    '10007': 'Lower Manhattan',
    '10038': 'Lower Manhattan',
    '10280': 'Lower Manhattan',
    '10002': 'Lower East Side',
    '10003': 'Lower East Side',
    '10009': 'Lower East Side',
    '10021': 'Upper East Side',
    '10028': 'Upper East Side',
    '10044': 'Upper East Side',
    '10065': 'Upper East Side',
    '10075': 'Upper East Side',
    '10128': 'Upper East Side',
    '10023': 'Upper West Side',
    '10024': 'Upper West Side',
    '10025': 'Upper West Side',
    '10031': 'Inwood and Washington Heights',
    '10032': 'Inwood and Washington Heights',
    '10033': 'Inwood and Washington Heights',
    '10034': 'Inwood and Washington Heights',
    '10040': 'Inwood and Washington Heights',
    '11361': 'Northeast Queens',
    '11362': 'Northeast Queens',
    '11363': 'Northeast Queens',
    '11364': 'Northeast Queens',
    '11354': 'North Queens',
    '11355': 'North Queens',
    '11356': 'North Queens',
    '11357': 'North Queens',
    '11358': 'North Queens',
    '11359': 'North Queens',
    '11360': 'North Queens',
    '11365': 'Central Queens',
    '11366': 'Central Queens',
    '11367': 'Central Queens',
    '11412': 'Jamaica',
    '11423': 'Jamaica',
    '11430': 'Jamaica',
    '11432': 'Jamaica',
    '11433': 'Jamaica',
    '11434': 'Jamaica',
    '11435': 'Jamaica',
    '11436': 'Jamaica',
    '11101': 'Northwest Queens',
    '11102': 'Northwest Queens',
    '11103': 'Northwest Queens',
    '11104': 'Northwest Queens',
    '11105': 'Northwest Queens',
    '11106': 'Northwest Queens',
    '11374': 'West Central Queens',
    '11375': 'West Central Queens',
    '11379': 'West Central Queens',
    '11385': 'West Central Queens',
    '11691': 'Rockaways',
    '11692': 'Rockaways',
    '11693': 'Rockaways',
    '11694': 'Rockaways',
    '11695': 'Rockaways',
    '11697': 'Rockaways',
    '11004': 'Southeast Queens',
    '11005': 'Southeast Queens',
    '11411': 'Southeast Queens',
    '11413': 'Southeast Queens',
    '11422': 'Southeast Queens',
    '11426': 'Southeast Queens',
    '11427': 'Southeast Queens',
    '11428': 'Southeast Queens',
    '11429': 'Southeast Queens',
    '11414': 'Southwest Queens',
    '11415': 'Southwest Queens',
    '11416': 'Southwest Queens',
    '11417': 'Southwest Queens',
    '11418': 'Southwest Queens',
    '11419': 'Southwest Queens',
    '11420': 'Southwest Queens',
    '11421': 'Southwest Queens',
    '11368': 'West Queens',
    '11369': 'West Queens',
    '11370': 'West Queens',
    '11372': 'West Queens',
    '11373': 'West Queens',
    '11377': 'West Queens',
    '11378': 'West Queens',
    '10302': 'Port Richmond',
    '10303': 'Port Richmond',
    '10310': 'Port Richmond',
    '10306': 'South Shore',
    '10307': 'South Shore',
    '10308': 'South Shore',
    '10309': 'South Shore',
    '10312': 'South Shore',
    '10301': 'Stapleton and St. George',
    '10304': 'Stapleton and St. George',
    '10305': 'Stapleton and St. George',
    '10314': 'Mid-Island',
    '': ''
}

violation_descriptions = {
    '4': 'Discontinue use of interior room for living or provide a single opening of at least 60 percent of area of the partition to room having window opening directly to street or yard',
    '6': 'Louvres or ventilators or windows or skylight',
    '7': 'Provide fixed ventilation of at least 40 sq.in. directly over stairwell',
    '8': 'Provide a ventilating skylight directly over the stairwell',
    '11': 'Make effective the light and ventilation of skylight by removing from beneath same the domelight located in ceiling',
    '51': 'Discontinue the storage of combustible material',
    '57': 'Discontinue the unlawful keeping of',
    '80': 'Provide legal second means of egress and file application for approval before doing the work',
    '81': 'Provide a sprinkler system or a legal second means of egress and file application for approval before doing this work',
    '106': 'A shoe properly secured to bottom of string of dropladder',
    '109': 'A stop at top of guide rods so as to prevent removal of dropladder',
    '118': 'Properly brace',
    '159': 'Safeguard egress by providing iron guard rails 3 ft 6 in high around skylight',
    '160': 'Of bulkhead/scuttle opening at roof',
    '176': 'Means of egress from yard to street by fireproof passageway for which application must be filed for approval,or by unlocked door or gate in fence to adjoining premises with consent of adjacent owner',
    '181': 'A fireproof passageway from fire escapes at rear to street and file application for approval before doing this work',
    '188': 'Properly fire retard in accordance with the rules and regulations of this department the cellar ceiling',
    '209': 'Remove door from closet leading to scuttle opening in roof at',
    '226': 'Under completed permit, a proper enclosure for the central heating plant,',
    '230': 'Provide an independent entrance from outside the dwelling to cellar and file application for approval before doing the work',
    '464': 'Provide a stationary iron ladder, extending from the sill of the lowest window to the bottom of',
    '483': 'Television and/or radio antenna to be at least 10 feet above roof and not attached to any fire escape or soil or vent line',
    '484': 'A completed certificate of inspection visits in a proper frame at or near mailboxes, bottom edge of frame between 48-62 inches above floor',
    '485': 'A completed certificate of inspection visits in a proper frame readily accessible for signature, bottom edge of frame between 48-62 inches above floor at',
    '491': 'Plans and application and legalize the following alteration or restore to the legal condition existing prior to the making of said alteration',
    '495': 'Plans and obtain a certificate of occupancy to legalize the following alteration or restore premises to prior legal condition',
    '496': 'Correct failure to comply with tenant notification requirements regarding internet capable temperature reporting devices. missing at public hall, 1st story',
    '497': 'Correct failure to install an internet capable temperature reporting device in one living room in apartment',
    '498': 'Correct failure to properly maintain a required internet capable temperature reporting device in apartment',
    '499': 'Correct failure to maintain required records regarding internet capable temperature reporting devices and submit such records to the department upon request',
    '500': 'Post and maintain a proper notice on wall of the entrance story in english and spanish on the availability of the agency’s housing information guide. a sample notice can be found at www.nyc.gov/hpd',
    '501': 'Properly repair the broken or defective',
    '502': 'Properly repair with similar material the broken or defective',
    '503': 'Make safe by properly repairing the structural defect',
    '504': 'Provide',
    '505': 'Replace with new the broken or defective',
    '506': 'Replace with new the missing',
    '507': 'Repair the roof so that it will not leak',
    '508': 'Repair the broken or defective plastered surfaces and paint in a uniform color',
    '509': 'Properly secure the loose',
    '510': 'Abate the nuisance consisting of',
    '511': 'Repair and operate the gas appliance so as to prevent carbon monoxide',
    '512': 'Fire escape defective. replace with new the broken, defective and/or missing',
    '513': 'Adjust the dropladder so that it will slide easily in the guide rods',
    '514': 'Fire escape defective. properly secure',
    '515': 'Fire escape defective. fill in holes in wall around brackets and/or rails',
    '516': 'Fire escape defective. reset the braces of the brackets so that they shall bear against wall',
    '517': 'Fire escape defective. remove and replace with new the broken and defective bracket and leave all anchorages uncovered for inspection',
    '518': 'Fire escape defective. replace with 2 x 1/2 inch iron bar extending across and secured to 2 brackets, the broken or defective angle iron or bar at foot of gooseneck ladder',
    '521': 'Fire egress defective. remove obstructing bars or unlawful gates from window to fire escape or provide approved type gate',
    '522': 'Fire egress defective. remove obstructing bars or unlawful gates from at least 1 window or provide approved type gate',
    '523': 'Fire egress defective. restore egress by removing locking device and arrange to open readily the gate in fence at lot line',
    '524': 'Fire egress defective. remove the obstruction in fireproof passageway',
    '525': 'Fire egress defective. make stationary the iron ladder leading to scuttle opening in roof',
    '526': 'Remove the illegal fastening',
    '527': 'Egress obstructed. provide proper means of egress by removing partitions forming closet enclosing scuttle ladder to roof',
    '528': 'Replace with standard wire glass the present glass',
    '529': 'Refit',
    '530': 'Arrange and make self-closing the doors',
    '531': 'Make stationary the transom over door',
    '534': 'Provide a proper seat for water closet',
    '535': 'Remove the torn and/or loose floor covering',
    '536': 'Remove device preventing door from being self-closing',
    '537': 'Remove unlawful wood or metal louvred or screen doors and assemblies from entrance to',
    '538': 'Remove all encumbrances consisting of',
    '539': 'Remove the encumbrance obstructing egress from fire escapes',
    '540': 'Replace refuse chute warning sign public hall door to service closet or on wall over hopper door',
    '541': 'Failure to distribute and post safe construction bill of rights and/or notice of the tenant protection plan. such notices shall remain posted until the completion of the described permitted work',
    '546': 'Remove the illegal double cylinder key operated locking device at door',
    '549': 'Abate the nuisance consisting of excessive storage of material',
    '550': 'Trace and repair the source and abate the nuisance consisting of mold ..',
    '551': 'Cleanse and disinfect to the satisfaction of this department after removing the',
    '552': 'Remove the accumulation of refuse and/or rubbish and maintain in a clean condition the',
    '553': 'Cleanse to the satisfaction of this department the',
    '554': 'Paint metal in accordance with dept. regulation',
    '556': 'Paint with light colored paint to the satisfaction of this department',
    '557': 'Remove the dirty and/or loose paper and repaper or paint to the satisfaction of this department',
    '558': 'No decorating in 3 years. paint with light colored paint to the satisfaction of this department',
    '559': 'No decorating in 3 years. remove the dirty and/or loose paper and repaper or paint to the satisfaction of this department',
    '561': 'Scrape and remove rust scales and paint with 2 coats of paint',
    '562': 'Paint to the satisfaction of this department the exterior window frames and sashes',
    '563': 'Thoroughly whitewash or paint with a light color the surfaces',
    '564': 'Thoroughly whitewash or paint with a light color the surfaces',
    '565': 'Thoroughly cleanse to the satisfaction of this department the dirty and unsanitary exterior walls at',
    '566': 'Abate the nuisance consisting of vermin',
    '567': 'Abate the infestation consisting of rodents',
    '568': 'Abate the infestation consisting of roaches',
    '569': 'Abate the infestation consisting of mice',
    '570': 'Abate the nuisance consisting of bedbugs',
    '571': 'Provide sufficient, proper and separate metal receptacles for the deposit of garbage, rubbish and other waste material and arrange for collection and disposal of such material',
    '572': 'Provide place within the building for the storage of waste receptacles and disinfect same regularly',
    '573': 'Post a sign indicating hours of collection and method of collection of waste material where dumbwaiter service is not provided',
    '576': 'Provide adequate supply of cold water for the fixtures',
    '577': 'Provide adequate supply of hot water for the fixtures',
    '578': 'Repair the leaky and/or defective water supply pipe',
    '579': 'Repair the leaky and/or defective faucets',
    '583': 'Properly repair the source and abate the evidence of a water leak',
    '588': 'Provide a suitable strainer for the drain',
    '589': 'Provide suitable tight cover for the handhole opening of trap',
    '591': 'Reset, so as to secure a proper and tight connection, the water closet bowl',
    '592': 'Replace with new the defective flush pipe of water closet',
    '593': 'Repair the flushing apparatus and maintain same so as to flush effectively the water closet',
    '594': 'Repair leaky water closet flush pipe connection',
    '595': 'Remove all obstructions from water closet',
    '596': 'Replace the broken or defective',
    '597': 'Remove disused plumbing fixtures and properly seal pipe connections',
    '598': 'Repair the broken or defective connection',
    '599': 'Repair by closing so as to be gas tight all openings in the',
    '600': 'Provide a proper screw cap for the cleanout of trap',
    '614': 'Certify compliance with lead-based paint hazard control requirements during period of unit vacancy - apartment _____',
    '616': 'Correct the lead-based paint hazard - presumed lead paint that is peeling or on a deteriorated subsurface using work practices set forth in 28 rcny §11-06(b)(2)',
    '617': 'Correct the lead-based paint hazard - paint that tested positive for lead content and that is peeling or on a deteriorated subsurface - using work practices set forth in 28 rcny §11-06(b)(2)',
    '618': 'Correct failure to provide to the department within 45 days of demand all records required to be maintained by owner',
    '619': 'Correct failure to notify occupants and/or to investigate lead-based paint hazards',
    '620': 'Correct failure to provide to the department within 45 days of demand all records required to be maintained by owner pursuant to local law 1 of 2004 related to lead-based paint notices, inspections and remediation/abatement activities',
    '621': 'Certify compliance with lead-based paint hazard control requirements during period of unit vacancy by performing activities necessary to abate presumed lead-based paint from required window and/or door friction surfaces for apartment and make floors smooth and cleanable, presumed lead paint in an apartment with a child under six',
    '622': 'Certify compliance with lead-based paint hazard control requirements during period of unit vacancy by performing activities necessary to abate tested lead-based paint from required window and/or door friction surfaces for apartment and make floors smooth and cleanable, positive lead-based paint in an apartment with a child under six ',
    '623': 'Certify compliance with lead-based paint hazard control requirements during period of unit vacancy by submitting required supporting documentation and affidavits ',
    '624': 'Correct the lead-based paint hazard-paint that is xrf tested inconclusive for lead content at 0.5mg/cm2 and is presumed lead paint and that is peeling or on a deteriorated subsurface',
    '625': 'Certify compliance with lead-based paint hazard control requirements during period of unit vacancy by performing activities necessary to abate presumed lead paint that is xrf tested inconclusive at 0.5 mg/cm2 (28 rcny √ø¬ø¬ω11-07(b)) from required window and/or door friction surfaces and make floors smooth and cleanable, in an apartment with a child under six located',
    '626': 'Certify compliance with the requirement to perform one investigation for the presence of lead-based paint through xrf testing in a dwelling unit within one year after a child under age six has come to reside after august 9, 2020 by submitting the required supporting documentation for apartment',
    '630': 'The following dwelling units were reoccupied while being subject to an order to repair/vacate order issued by the department; order conditions observed existing',
    '631': 'The following dwelling units were reoccupied while being subject to an order to repair/vacate order issued by the department; file for a dismissal request related to the issued order (see www.nyc.gov/hpd)',
    '632': 'Order to repair/vacate order must remain posted until such time as the order is rescinded. a copy for posting can be found through hpdonline (www.nyc.gov/hpd)',
    '649': 'Remove all obstructions and repair all defects in',
    '652': 'Repair the broken or defective rain leader',
    '654': 'Repair the broken or defective gutter',
    '657': 'Remove the broken or defective flooring and pave the floor with 4 inches of concrete',
    '658': 'Properly repair the broken or defective paving',
    '659': 'Grade with proper slope to existing drain and pave with 4 inches of concrete the surface',
    '664': 'Provide an adequate supply of heat from an approved central heating system, or an approved system of gas or electrical heating in good operating condition for the dwelling unit',
    '665': 'Install central heating system or, if lawfully feasible, individual space heaters, and file an application for approval before doing work',
    '666': 'Provide an adequate supply of heat for the apartment',
    '670': 'Provide hot water at all hot water fixtures',
    '671': 'Post notice, in form approved by the department, stating the name and location of the person designated by the owner to have key to buildings heating system',
    '672': 'Provide ready access to buildings heating system',
    '674': 'Device present on central heating system which is capable of causing an otherwise operable system to become inoperable',
    '675': 'Discontinue use of illegal space and/or hot water heater and provide filed for & approved heater which obtains combustion air directly from outside the building or approved central system',
    '680': 'Provide adequate lighting for the laundry room',
    '681': 'Provide a proper means of lighting for water closet compartment',
    '682': 'Provide adequate lighting for',
    '683': 'Provide adequate light of not less than 60 watts incandescent or equivalent illumination',
    '684': 'Provide adequate lighting',
    '685': 'Provide and maintain a light directly over the mail boxes in public hall',
    '686': 'Provide adequate lighting at or near the outside of the front entranceway of the building and keep same burning from sunset every day to sunrise on the day following',
    '687': 'Install and maintain sufficient light or lights of at least 100 watts incandescent or equivalent each, to light adequately from sunset to sunrise the',
    '688': 'Provide a safe and adequate supply of electric service to the fixtures',
    '689': 'Properly repair and abate unsafe electric wiring condition consisting of',
    '690': 'Provide a peep hole in entrance door of the dwelling unit so located so as to permit a person inside the dwelling to view any person outside entrance door',
    '691': 'Provide a mirror in self-service elevator arranged so as to enable a person entering, to view inside of elevator number',
    '692': 'Provide a lock and key to the entrance door of dwelling unit and, if a cl a multiple dwelling, also',
    '693': 'Arrange and make self-closing the doors',
    '694': 'Replace with wire glass the present glass in doors and/or transoms',
    '695': 'Remove unlawful sash in partition separating apartment from public hall and seal opening with fire retarded material',
    '697': 'Provide approved one-hour fire resistance rated self-closing door with key-operated dead bolt & latch set, peep hole & chain guard at main entrance to',
    '698': 'Provide approved one-hour fire resistance rated self-closing door at all openings to public hall other than apt main entrance door from',
    '700': 'Post a proper notice of smoke detector requirements, in a form approved by the commissioner, at or near the mail box',
    '701': 'Provide an approved and operational smoke detecting device, installed in accordance with department of buildings rules and regulations',
    '702': 'Repair or replace the smoke detector',
    '703': 'File certification of satisfactory installation of smoke detecting device in accordance with h.p.d. rules and regulations',
    '704': 'Maintain on the premises and make available to the department upon request records of installation and maintenance of smoke detectors in the building',
    '706': 'Arrange for mail to be delivered to owner, his agent or employees for prompt distribution to occupants',
    '707': 'Provide and maintain approved mail receptacles and directories for the persons residing in the dwelling as provided in the u.s. postal regulations',
    '708': 'Paint or post a sign indicating floors',
    '709': 'Post and maintain a street number on the front of the dwelling plainly visible from the sidewalk',
    '711': 'Maintain on the premises a copy of the sprinkler test for the current year',
    '712': 'Provide an angle hose valve or sill cock at extreme end of highest line of sprinklers',
    '713': 'Provide a piece of garden hose 10 feet in length with female coupling and a 10 quart pail on premises to test sprinkler system',
    '714': 'Seal in open position the o.s.y. valve of the sprinkler system in accordance with the rules and regulations of this department',
    '715': 'Provide 3 extra sprinkler heads and suitable wrench for emergency purposes at o.s.y. valve of sprinkler in accordance with the rules and regulations of this department',
    '716': 'Provide a manager who shall be responsible for the conduct, operation and maintenance of premises and who shall live on premises or be regularly present therein',
    '717': 'Provide an adequate supply of water for the wet sprinkler and/or standpipe system at',
    '721': 'Provide dwelling with a janitor or responsible person or janitorial service',
    '722': 'Post sign on wall of entrance story bearing name, address including apartment number if any, and telephone number of superintendent, janitor or housekeeper',
    '726': 'Discontinue use of interior room for living or provide an alcove opening of at least 32# sq ft to room having a window opening directly to street or yard',
    '727': 'Discontinue use of interior room for living',
    '728': 'Post and maintain a notice, written in english and in spanish, on the building entrance door or other conspicuous location in the building common area, stating that: (1) the building is in the alternative enforcement program, (2) that occupants may call 311 or the aep at 212-863-8262 to report housing maintenance complaints, (3) the name, telephone, and address of the owner, and, (4) the identity of any financial institution that holds a mortgage on the property. post',
    '731': 'Provide proper plastered partitions extending from floor to ceiling for water closet compartment and/or bathroom',
    '732': 'Provide in accordance with the rules and regulations of this department a waterproof floor and base for the water closet',
    '733': 'Provide ventilation for water closet compartment and/or bathroom and file application for approval before doing work',
    '741': 'Discontinue unlawful cooking space or file plans and application with this department to legalize same, if lawfully feasible,',
    '742': 'Provide an adequate supply of gas to the fixtures',
    '744': 'Control knob safety covers for the gas stove',
    '746': 'Discontinue unlawful overcrowding',
    '749': 'Discontunue unlawful use of kitchen for sleeping purposes',
    '750': 'Discontinue unlawful occupancy for living purposes by child or children under 16 years of age',
    '751': 'Discontinue the rooming unit',
    '752': 'Discontinue use for single room occupancy purposes the apartments which are occupied by more than 2 boarders, roomers or lodgers',
    '753': 'Discontinue unlawful use for single room occupancy purposes',
    '754': 'Discontinue the unlawful use as separately occupied sleeping rooms or, provide unobstructed access to each required means of egress',
    '755': 'Discontinue the use of the premises for single room occupancy',
    '761': 'Discontinue use of rooms for living, disconnect plumbing fixtures and properly seal pipe connections',
    '762': 'Discontinue use of rooms for living purposes',
    '764': 'Discontinue use for living',
    '768': 'The premises formerly a vacant building are now occupied by other than a caretaker without obtaining a certificate of occupancy',
    '771': 'File with this department a true registration statement for building',
    '772': 'File with this department a registration statement for building',
    '773': 'File with this department a telephone number at which the owner or a responsible person can be reached at all hours in the event of an emergency',
    '776': 'File with this department a registration statement with a proper address for registered party',
    '778': 'Post and maintain a proper sign on wall of entrance story showing the registration number assigned by the department and the address of the building',
    '790': 'Missing or repair/replace the defective window guard(s) in accordance with the specifications of the new york city health code section 24 rcny chapter 12',
    '791': 'Missing or repair/replace the defective window guard(s) throughout the public areas in accordance with the specifications of the new york city health code section 24 rcny chapter 12',
    '801': 'Properly repair the broken or defective',
    '802': 'Properly repair with similar material the broken or defective',
    '803': 'Make safe by properly repairing the structural defect',
    '804': 'Provide',
    '805': 'Replace with new the broken or defective',
    '806': 'Replace with new the missing',
    '807': 'Repair the roof so that it will not leak',
    '808': 'Repair the broken or defective plastered surfaces and paint in uniform color',
    '809': 'Properly secure the loose',
    '810': 'Abate the nuisance consisting of',
    '812': 'Fire escape defective. replace with new the broken, defective and/or missing',
    '813': 'Fire escape defective. adjust the dropladder so that it will slide easily in the guide rods',
    '814': 'Fire escape defective. properly secure',
    '821': 'Fire egress defective. remove obstructing bars or gates from window to fire escape',
    '822': 'Fire egress defective. remove obstructing bars or gates from at least 1 window',
    '826': 'Remove the illegal fastening',
    '829': 'Refit',
    '834': 'Provide a proper seat for water closet',
    '835': 'Remove the torn and/or loose floor covering',
    '838': 'Remove all encumbrances consisting of',
    '839': 'Remove the encumbrance obstructing egress from fire escapes',
    '846': 'Remove the illegal double cylinder key operated locking device at door',
    '849': 'Abate the nuisance consisting of excessive storage of material',
    '851': 'Cleanse and disinfect to the satisfaction of this department after removing the',
    '852': 'Remove the accumulation of refuse and/or rubbish and maintain in a clean condition the',
    '853': 'Cleanse to the satisfaction of this department the',
    '856': 'Paint with light colored paint to the satisfaction of this department',
    '857': 'Remove the dirty and/or loose paper and repaper or paint to the satisfaction of this department',
    '861': 'Scrape and remove rust scales and paint with two coats of paint the',
    '866': 'Abate the nuisance consisting of vermin',
    '867': 'Abate the infestation consisting of rodents',
    '868': 'Abate the infestation consisting of roaches',
    '869': 'Abate the infestation consisting of mice',
    '870': 'Abate the nuisance consisting of bedbugs',
    '871': 'Provide sufficient,proper and separate metal receptacles for the deposit of garbage, rubbish and other waste material and arrange for collection and disposal of such material',
    '872': 'Provide place within the building for the storage of waste receptacles and disinfect same regularly',
    '876': 'Provide adequate supply of cold water for the fixtures',
    '877': 'Provide adequate supply of hot water for the fixtures',
    '878': 'Repair the leaky and/or defective water supply pipe',
    '879': 'Repair the leaky and/or defective faucets',
    '883': 'Properly repair the source and abate the evidence of a water leak',
    '888': 'Provide suitable strainer for the drain',
    '889': 'Provide suitable tight cover for handhole opening of trap',
    '891': 'Reset, so as to secure a proper and tight connection, the water closet bowl',
    '892': 'Replace with new the defective flush pipe of water closet',
    '893': 'Repair the flushing apparatus and maintain same so as to flush effectively the water closet',
    '894': 'Repair leaky water closet flush pipe connection',
    '895': 'Remove all obstructions from water closet',
    '896': 'Replace the broken or defective',
    '897': 'Remove disused plumbing fixtures and properly seal pipe connections',
    '898': 'Repair the broken or defective connection',
    '899': 'Repair by closing so as to be gas tight all openings in the',
    '946': 'Properly close and seal opening as described below6',
    '949': 'Remove all obstructions and repair all defects in',
    '950': 'Provide properly trapped, sewer connected, rain leader so as to provide proper drainage and file an application for approval before doing the work',
    '952': 'Repair the broken or defective rain leader',
    '953': 'Provide a gutter, properly connected to drainage system, for proper drainage',
    '954': 'Repair the broken or defective gutter',
    '958': 'Properly repair the broken or defective paving',
    '960': 'Regrade with proper slope to existing drain the surface',
    '964': 'Provide an adequate supply of heat from an approved central heating system or an approved system of gas or electrical heating in good operating condition for the dwelling unit',
    '966': 'Provide an adequate supply of heat for the apartment',
    '970': 'Provide hot water at all hot water fixtures',
    '975': 'Discontinue use of illegal space and/or hot water heater and provide filed for & approved heater which obtains combustion air directly from outside the building or approved central system',
    '981': 'Provide proper means of lighting for water closet compartment',
    '982': 'Provide adequate lighting for',
    '988': 'Provide a safe and adequate supply of electric service to the fixtures',
    '989': 'Properly repair and abate unsafe electric wiring condition consisting of',
    '990': 'A peep hole in entrance door of the dwelling unit so located as to permit a person inside the dwelling unit to view any person outside entrance door',
    '1002': 'Repair or replace smoke detector',
    '1003': 'File certification of satisfactory installation of smoke detecting device in accordance with hpd rules and regulations',
    '1009': 'Post and maintain a street number on the front of the dwelling plainly visible from the sidewalk',
    '1026': 'Discontinue use of interior room for living or provide an alcove opening of at least 32 1/2 sq.ft. to room having a window opening directly to street or yard',
    '1028': 'Discontinue the use of the interior room for living or provide an alcove opening of 60 sq.ft. to a room having a window opening directly to street or yard',
    '1032': 'Provide in accordance with the rules and regulations of this department a waterproof floor and base for the water closet',
    '1033': 'Provide ventilation for water closet compartment and/ or bathroom and file application for approval before doing work',
    '1041': 'Discontinue unlawful cooking space or file plans and application with this department to legalize same, if lawfully feasible',
    '1042': 'Provide an adequate supply of gas to the fixtures',
    '1051': 'Discontinue the rooming unit',
    '1054': 'Discontinue the unlawful occupancy by more than two roomers, boarders or lodgers',
    '1061': 'Discontinue use of rooms for living, disconnect plumbing fixtures where illegal and properly seal pipe connections',
    '1062': 'Discontinue use of rooms for living purposes or obtain a certificate of occupancy',
    '1492': 'Plans and application and obtain a certificate of occupancy to legalize the conversion from a private dwelling to multiple dwelling use if lawfully feasible or restore to lawful occupancy',
    '1493': 'Frame building has been converted from a private dwelling to a multiple dwelling and is now occupied and maintained as such contrary to law.restore premises to lawful occupancy',
    '1499': 'Immediately provide a fire guard as directed by the nyc dept. of housing preservation & development (hpd) and/or the nyc dept. of buildings (dob) to protect against fire hazards observed by hpd and/or dob. ',
    '1501': 'Of carbon monoxide detecting device requirements, in a form approved by the commissioner, in a common area of a class a multiple dwelling near inspection certificate or provide notice to tenants in a private dwelling',
    '1502': 'An approved and operational carbon monoxide detecting device, installed in accordance with applicable law and rules',
    '1503': 'The carbon monoxide detecting device(s)',
    '1505': 'Premises and make available to the department upon request records of installation and maintenance of carbon monoxide detecting device(s) in the building',
    '1506': 'Post, in a form approved by the commissioner, and maintain a notice in a common area of the building regarding the procedures that should be followed when a gas leak is suspected',
    '1507': 'File annual bedbug report in accordance with hpd rule as described on the back of this notice of violation or as described on hpd?s website, www.nyc.gov\hpd, search bed bugs',
    '1508': 'Post at or near the mailboxes or distribute to each tenant upon commencement of new lease or upon lease renewal, in the form approved by the commissioner, the annual bedbug report and a copy of the dohmh preventing and getting rid of bedbugs safely guide, according to the certification made on such annual bedbug report',
    '1509': 'Post, in the form approved by the commissioner, and maintain the notice about prevention, detection and removal of bedbug infestation',
    '1524': 'Provide written notice to the tenants at least twenty-four hours prior to essential service interruption by posting a notice in a prominent place within the public part of the building and on each floor of such building, where an owner must make a repair that may result in an interruption of essential services such as utilities(heat, hot water, gas, electricity, or elevator) that is expected to continue for more than two hours. sample notice available at www.nyc.gov/hpd or as provided in this notice of violation. no hot water services to entire building',
    '': ''
}